### ISSUE TITLE
Flaticon API anbinden

### ISSUE THREAD

**Issue by schmitzhermes** [L21s/powerpoint-addin#4]
Wäre geil, wenn wir diese API nutzen könnten: 
https://api.flaticon.com/v3/docs/index.html

direkt schon gefiltert nach "Basic Miscellany Lineal" und die Icons in unseren Unternehmensfarben (schwarz / weiß / blau / pink) einfärbbar

keine Ahnung ob das geht, aber wäre geil

**Comment by fabiankuenzer** [comment]
@EinfachMarwin Bitte einen neuen API Key erstellen: https://www.freepik.com/api
